### ISSUE TITLE
how to run your code?

### ISSUE THREAD

**Issue by richardvancouver** [danielktaylor/PyLimitBook#1]
sudo python tseries.py? how to input data?

**Comment by danielktaylor** [comment]
Create a CSV file in the format described in the README and pass it into one of the 4 python programs under python 2.

**Comment by richardvancouver** [comment]
how to pass csv file into python?

*.csv > *.py ?

**Comment by danielktaylor** [comment]
Unfortunately, this is not intended to be an end-user product. It is more a code sample for you to modify. If you are not familiar with Python and the command line, the project won't be very useful to you.

**Comment by richardvancouver** [comment]
I ran it, I used 'python *.py *.csv

The error I met is :

/PyLimitBook-master$ python parse.py XOM_BATS_2010-11-10.csv

Input: B,XOM,BATS,571233,100,5.0,31016608

Traceback (most recent call last):
  File "parse.py", line 26, in <module>
    print (quotebook)
  File
"/home/rui/Desktop/QUANT/matchingsimulation/PyLimitBook-master/book.py",
line 83, in **str**
    file_str.write('%s' % v)
  File
"/home/rui/Desktop/QUANT/matchingsimulation/PyLimitBook-master/orderList.py",
line 84, in **str**
    for order in self:
TypeError: iter() returned non-iterator of type 'OrderList'

**Comment by danielktaylor** [comment]
Running Python 2.7.10 with the sample data and parse.py:

```
LM-SJN-00876446:PyLimitBook-master $ python parse.py sample_data/XOM_BATS_2010-11-10.csv


Input: B,XOM,BATS,571233,100,5.0,31016608

------ Bids -------
100 @   5.0000

------ Asks -------

------ Trades ------
```

**Comment by richardvancouver** [comment]
The code runs OK. Another question, does your code simulate matching of
prices (such as market order or limit order matching)? Thank you very much!

Best,
R.Yang

**Comment by danielktaylor** [comment]
No unfortunately is does not do any matching simulation.
