### ISSUE TITLE
Order matching

### ISSUE THREAD

**Issue by brdsio** [danielktaylor/PyLimitBook#2]
Hi Daniel,
In your opinion, what is the best architecture to implement order matching?
Thx

**Comment by danielktaylor** [comment]
Hi Flavio,

I haven't kept up much on the state of the art in exchange-side matching, there is a naive implementation in the backtester: https://github.com/danielktaylor/PyStrategies/tree/master/backtest/TradingFramework4j

I've watched some of the talks by these guys, and it might be useful for you:

https://lmax-exchange.github.io/disruptor/

**Comment by brdsio** [comment]
Thank you
