### ISSUE TITLE
issue in "update_order"?

### ISSUE THREAD

**Issue by cealvara** [danielktaylor/PyLimitBook#7]
Hi,

Thanks a lot for your work on this. I wanted to raise a possible issue with the update_order method in the Tree class.

When you have an order that's been modified in price, you correctly "delete" that order and insert a new one (to replace the price and priority).

However, I think you are not updating the Tree volume correctly, because when you insert the new order the order.quantity gets duplicated.

Please correct me if I'm wrong.

Best,
Carlos A.

**Comment by danielktaylor** [comment]
Hi @cealvara 

I'll take a look and see if I can reproduce.

**Comment by danielktaylor** [comment]
This is a bug; thank you for reporting this. I will submit a fix shortly. It can be easily reproduced:

```python
#!/usr/bin/python
from pylimitbook import researchBook

lines = (
    # type, symbol, id, qty, price,  timestamp
    ["ask", "XYZ",  1,  100, "0.50", 9000],
    ["bid", "XYZ",  2,  200, "0.49", 9001],
    ["ask", "XYZ",  3,  150, "0.51", 9002],
    ["ask", "XYZ",  1,  100, "0.52", 9003],
)

book = researchBook.ResearchBook()

for line in lines:
    if line[0] == "ask":
        book.ask_split(*line[1:])
    else:
        book.bid_split(*line[1:])

    print line[1:]
    print "Ask volume: %i" % book.ask_volume
    print "Bid volume: %i" % book.bid_volume
    print ""

print str(book)
```

**Comment by cealvara** [comment]
great, thanks!

**Comment by danielktaylor** [comment]
@cealvara merged a fix for this - thanks for your help.
